# Generated by Django 2.2 on 2020-03-23 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_regist_app', '0001_initial'),
        ('quote_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='likes',
            new_name='like_count',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='login_regist_app.User')),
                ('liked_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='quote_app.Quote')),
            ],
        ),
    ]
